name: challange

on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Print ubuntu date
        run: date
  second:
    runs-on: windows-latest
    steps:
      - name: Print windows date
        run: Get-Date
  third:
    runs-on: macos-latest
    steps:
      - name: Print macos date
        run: date
  final:
    runs-on: ubuntu-latest
    needs: [first, second, third]
    steps:
      - name: Print success
        run: echo 'Successful date prints, yay!'