name: Secrets and Variables

on: [push] # can also be triggered on multiple events eg. [push, pull_request]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup secrets
        uses: actions/checkout@v2
        with:
          some_secret: ${{ secrets.TEST_SECRET }}
      - name: Do something
        run : echo $some_secret
